[package]
name = "nebulet"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]

[package.metadata.bootimage]
default-target = "x86_64-nebulet.json"
output = "bootimage.bin"

# We're pulling down the pre-compiled bootloader, so no
# need to build it. (Also avoids a bug in xargo)
#[package.metadata.bootimage.bootloader]
#git = "https://github.com/rust-osdev/bootloader.git"

[profile.release]
lto = true
panic = "abort"
# for debugging in release mode
# debug-assertions = true
# debug = true
# overflow-checks = true

[workspace]
members = [
    "tools",
    "lib/nil",
    "lib/nebulet-derive",
]
exclude = [
    "target/x86_64-nebulet/release/bootloader",
    "target/x86_64-nebulet/debug/bootloader",
    "cretonne",
]

[features]
default = ["vga", "serial"]
vga = [] # log to vga
serial = [] # log to serial

[dependencies]
spin = "0.4.6"
bitflags = "1.0"
bit_field = "0.9.0"
raw-cpuid = "3.1.0"

x86_64 = "0.2.0-alpha-019"
os_bootinfo = "0.2.0"
hashmap_core = "0.1.5"

# lib/
[dependencies.nil]
path = "lib/nil"
[dependencies.nebulet-derive]
path = "lib/nebulet-derive"

[dependencies.lazy_static]
version = "1.0.0"
features = ["spin_no_std"]

[dependencies.rand_core]
version = "0.2"
default-features = false

[dependencies.nebulet_abi]
path = "nabi"

# Cretonne compiler
[dependencies.cretonne-codegen]
path = "cretonne/lib/codegen"
default-features = false
features = ["core"]

[dependencies.cretonne-frontend]
path = "cretonne/lib/frontend"
default-features = false
features = ["core"]

[dependencies.cretonne-wasm]
path = "cretonne/lib/wasm"
default-features = false
features = ["core"]

[dependencies.cretonne-native]
path = "cretonne/lib/native"
default-features = false
features = ["core"]

[dependencies.wasmparser]
version = "0.16.0"
default_features = false
features = ["core"]
